### ISSUE TITLE
Feature request: sorting

### ISSUE THREAD

**Issue by chuck-wood** [chuck-wood/download-all-attachments#12]
Currently the list of attachments in the sidebar is sorted alphabetically. It would be helpful to be able to sort them by other attributes, such as timestamp.

**Comment by swijchers** [comment]
_This app is now maintained and supported by [Sparkly](https://sparkly.dev/). Although the app is available for free in the [marketplace](https://www.zendesk.com/apps/support/102131/download-all-attachments/), the new versions are no longer open source. We would like to thank Charles Wood for his great work!_

As attachments are grouped by comment now, sorting is no longer necessary.
