### ISSUE TITLE
Doesn't find inline attachments

### ISSUE THREAD

**Issue by chuck-wood** [chuck-wood/download-all-attachments#14]
If images are copy-pasted directly into the body of a ticket, they are not found by this app. It's probably a relatively recent change by Zendesk, and would be a relatively small change to include them.

**Comment by swijchers** [comment]
_This app is now maintained and supported by [Sparkly](https://sparkly.dev/). Although the app is available for free in the [marketplace](https://www.zendesk.com/apps/support/102131/download-all-attachments/), the new versions are no longer open source. We would like to thank Charles Wood for his great work!_

Inline attachments are also shown. Can be disabled from the settings page.
