### ISSUE TITLE
Preview on hover

### ISSUE THREAD

**Issue by chuck-wood** [chuck-wood/download-all-attachments#2]
Show a preview of the file on hover instead of having to click through. This may be impractical, since I can't generate thumbnails... _or can I_???

**Comment by swijchers** [comment]
_This app is now maintained and supported by [Sparkly](https://sparkly.dev/). Although the app is available for free in the [marketplace](https://www.zendesk.com/apps/support/102131/download-all-attachments/), the new versions are no longer open source. We would like to thank Charles Wood for his great work!_

Image attachments show a preview on hover now:
![image](https://user-images.githubusercontent.com/20306091/143197324-a751ccdd-8def-4422-a5e6-140ad66f7a14.png)
