### ISSUE TITLE
Group attachments by comment

### ISSUE THREAD

**Issue by chuck-wood** [chuck-wood/download-all-attachments#3]
Somehow group attachments in the preview list to indicate that they were from different comments. This may be a good way to easily pick out the handful of files you want instead of having to download everybody's fancy signatures.

**Comment by swijchers** [comment]
_This app is now maintained and supported by [Sparkly](https://sparkly.dev/). Although the app is available for free in the [marketplace](https://www.zendesk.com/apps/support/102131/download-all-attachments/), the new versions are no longer open source. We would like to thank Charles Wood for his great work!_

Attachments are now grouped by comment and can be easily (de)selected per comment.

![image](https://user-images.githubusercontent.com/20306091/143198782-b81d0baf-d889-4a8d-8b54-ac9d4df25fe8.png)
