### ISSUE TITLE
Monitor for new attachments

### ISSUE THREAD

**Issue by chuck-wood** [chuck-wood/download-all-attachments#4]
If someone sends an update with more attachments while you're viewing the ticket, update to include the new attachments.

(This should be doable with the `ticket.comments.changed` event.)

**Comment by swijchers** [comment]
_This app is now maintained and supported by [Sparkly](https://sparkly.dev/). Although the app is available for free in the [marketplace](https://www.zendesk.com/apps/support/102131/download-all-attachments/), the new versions are no longer open source. We would like to thank Charles Wood for his great work!_

The app now listens to the `ticket.comments.changed` event and will add any incoming attachments.
