### ISSUE TITLE
Issue when multiple attachments have same filename

### ISSUE THREAD

**Issue by ilovelofi** [chuck-wood/download-all-attachments#6]
Love the app! Just one problem: it looks like if a ticket has multiple attachments with the same filename, it will only include one of the attachments in the download, even if the files themselves are different. Any way this can be fixed?

**Comment by chuck-wood** [comment]
Hi, thanks for raising an issue, sorry for the delayed response. I will take a look at this one.

**Comment by chuck-wood** [comment]
Fixed by using first 8 characters of the token that Zendesk creates for each attachment. These are pretty likely to be unique and don't require me to reinvent the wheel. Only downside is they're pretty ugly.

**Comment by chuck-wood** [comment]
Note that it takes a couple of weeks to update the app in the App Store.

**Comment by ilovelofi** [comment]
Thanks, Chuck! Love this app!

**Comment by chuck-wood** [comment]
This has been approved and published by Zendesk. The new application version is 1.0.1. Cheers!

**Comment by chuck-wood** [comment]
Also note that I found existing code to add numbers in parentheses for deduplication (like how Windows does it), which I find to be more readable than using the Zendesk token.
