### ISSUE TITLE
Link to app's settings page

### ISSUE THREAD

**Issue by chuck-wood** [chuck-wood/download-all-attachments#9]
As I make the behavior more complex, I want to assist users who prefer the simple interface. Linking to the settings page for the app will make it easy to disable features they don't care for.

**Comment by swijchers** [comment]
_This app is now maintained and supported by [Sparkly](https://sparkly.dev/). Although the app is available for free in the [marketplace](https://www.zendesk.com/apps/support/102131/download-all-attachments/), the new versions are no longer open source. We would like to thank Charles Wood for his great work!_

As app settings are moving to Admin Center, we've moved the app settings to the `nav_bar` location. The native app settings page is no longer being used. Any upcoming settings will be configurable here.

![image](https://user-images.githubusercontent.com/20306091/143199640-aa355ea2-56c8-463f-9efc-144427e94182.png)
